//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45_TEAM01A_LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class booklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booklist()
        {
            this.Issue_Details = new HashSet<Issue_Details>();
        }
    
        public string ISBN { get; set; }
        public string Title { get; set; }
        public int Book_ID { get; set; }
        public string Language { get; set; }
        public string Category { get; set; }
        public string Author { get; set; }
        public Nullable<int> Year_of_Publication { get; set; }
        public string Disposed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Details> Issue_Details { get; set; }
    }
}
